version: "3.7"

services:
  sampleapp:
    container_name: sampleapp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "80:8080"